# Source: cluster-api-aws/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cb345908-519e-4f4c-b704-80a9e64db4b3
  namespace: cb345908-519e-4f4c-b704-80a9e64db4b3
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: cb345908-519e-4f4c-b704-80a9e64db4b3
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "cb345908-519e-4f4c-b704-80a9e64db4b3-control-plane"
